### ISSUE TITLE
Make Title Search Better Match Expectations

### ISSUE THREAD

**Issue by bhens14** [ksscott/VotingMachine#17]
The title search needs to match users' expectations better. This can start by matching the first characters of a name before matching any characters in a name.

**Comment by ksscott** [comment]
The text matching logic happens in `/src/main/Session.interpret()`.
I recommend calling `.sorted()` on the stream, passing in a custom comparator that first checks `option.name().toLowerCase().startsWith(input.toLowerCase())`. Instead of finding `.findAny()`, you'll need to `.findFirst()`.
